name: 'Cache builds of Nix flake attributes'
description: 'Use the GitHub Actions cache for Nix flake attribute builds'
author: 'Rik Huijzer'
inputs:
  key:
    description: 'An explicit key for restoring and saving the cache'
    required: true
  flake_paths:
    description: 'Flake paths to cache builds of, defaults to `.#devShells.x86_64-linux.default`.'
    default: '.#devShells.x86_64-linux.default'
outputs:
  cache-hit:
    description: 'A boolean value to indicate an exact match was found for the primary key'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'arrow-down'
  color: 'blue'
